<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/2_Valores_Nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**VALORES NULOS**

In [11]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('Citas_Digital_Filtrado.csv', index_col=False)
data.head(5)

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
0,Saul,NaN,Guillermo,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s..."
1,Saul,NaN,Roberto,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso
2,Saul,NaN,Irving,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso
3,Saul,NaN,Oswaldo,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as..."
4,Saul,NaN,Rodrigo,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...

In [8]:
#Identificar valores nulos por columna
valores_nulos=data.isnull().sum()
valores_nulos

BDC                                          16
Fecha                                       601
Nombre Cliente                               21
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         180
¿Por que no hay solicitud de credito?       294
¿Por que no hubo prueba de manejo ?         318
¿Por que no hubo proceso wow?               309
¿Por que se asigno antes de vistar piso?    320
dtype: int64

In [10]:
#Identificar valores nulos por dataframe
valores_nulos=data.isnull().sum().sum()
valores_nulos

np.int64(2208)

**Métodos de Sustitución de Valores Nulos**

In [15]:
data_limpia = data.copy()

In [ ]:
# Quitar espacios en blanco al inicio y al final de los nombres de las columnas
data_limpia.columns = data_limpia.columns.str.strip()

In [48]:
print(data_limpia.dtypes)

BDC                                             str
Fecha                                           str
Nombre Cliente                                  str
Estatus de Lead                                 str
Potencial de compra                             str
PDM                                         float64
SDC                                         float64
Venta                                       float64
Asesor Asignado                                 str
¿Por que no ha visitado la agencia?             str
¿Por que no hay solicitud de credito?           str
¿Por que no hubo prueba de manejo ?             str
¿Por que no hubo proceso wow?                   str
¿Por que se asigno antes de vistar piso?        str
dtype: object

In [ ]:
data_limpia['Potencial de compra'] = pd.to_numeric(data_limpia['Potencial de compra'], errors='coerce')

In [52]:
print(data_limpia.dtypes)

BDC                                             str
Fecha                                           str
Nombre Cliente                                  str
Estatus de Lead                                 str
Potencial de compra                         float64
PDM                                         float64
SDC                                         float64
Venta                                       float64
Asesor Asignado                                 str
¿Por que no ha visitado la agencia?             str
¿Por que no hay solicitud de credito?           str
¿Por que no hubo prueba de manejo ?             str
¿Por que no hubo proceso wow?                   str
¿Por que se asigno antes de vistar piso?        str
dtype: object

In [82]:
# 1. Rellenar los valores nulos de la columna 'BDC' 

data_limpia['BDC'] = data_limpia['BDC'].fillna("Sin BDC")

Elegoi la opción de sustitución por un valor de texto específico "Sin BDC", debido a que es una variable categórica y no es posible aplicar medidas estadísticas como la media o mediana. Se evita utilizar ffill o bfill porque el valor de una fila no necesariamente corresponde al de la fila siguiente o anterior.

In [22]:
data_limpia.isnull().sum()

BDC                                           0
Fecha                                       601
Nombre Cliente                               21
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         180
¿Por que no hay solicitud de credito?       294
¿Por que no hubo prueba de manejo ?         318
¿Por que no hubo proceso wow?               309
¿Por que se asigno antes de vistar piso?    320
dtype: int64

In [ ]:
# 2 Rellenar los valores nulos de la columna Fecha de Cita
data_limpia['Fecha'] = data_limpia['Fecha'].ffill()

In [76]:
print(data_limpia['Fecha'])

0      2026-06-01
1      2026-06-01
2      2026-06-01
3      2026-06-01
4      2026-06-01
          ...
668    2026-07-21
669    2026-07-21
670    2026-07-22
671    2026-07-22
672    2026-07-22
Name: Fecha, Length: 673, dtype: str

Se uso para preserva la secuencia cronológica lógica del registro de fechas, garantizando que cada lead quede agrupado en el bloque temporal más cercano sin alterar la continuidad del conjunto de datos.

In [28]:
data_limpia.isna().sum()

BDC                                           0
Fecha                                         0
Nombre Cliente                               21
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         180
¿Por que no hay solicitud de credito?       294
¿Por que no hubo prueba de manejo ?         318
¿Por que no hubo proceso wow?               309
¿Por que se asigno antes de vistar piso?    320
dtype: int64

In [ ]:
# 3 Rellenar valores nulos de la columna Nombre de Cliente 
data_limpia = data_limpia.dropna(subset=['Nombre Cliente'])

Decidi borrar las filas porque no representan interacciones reales ni citas, entonces son errores de formato/diseño del reporte visual original. Al quitarlos evitamos confuciones e evita Sesgos en Métricas Si se conservan o se imputan y asi no arruinan los calculos de tasa de conversión de la agencia.

In [ ]:
# 4 limpiar valores Nulos de la columna Estatus de Lead  
data_limpia['Estatus de Lead'] = data_limpia['Estatus de Lead'].fillna("Sin Estatus")

Decidi rellenarlo con "Sin Estatus" ya que no se puede determinar el estatus de un lead sin información.

In [41]:
data_limpia.isnull().sum()

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Estatus de Lead                               0
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         180
¿Por que no hay solicitud de credito?       294
¿Por que no hubo prueba de manejo ?         318
¿Por que no hubo proceso wow?               309
¿Por que se asigno antes de vistar piso?    320
dtype: int64

In [ ]:
# 5 limpiar valores Nulos de la columna Potencial de compra con mediana 

data_limpia['Potencial de compra'] = data_limpia['Potencial de compra'].fillna(data_limpia['Potencial de compra'].median())

se relleno con mediana ya que es una columna numerica y por lo mismo usar mediana es menos sensible a valores extremos que la media. De esta manera se pueden conservar los registros sin modificar excesivamente la distribución de la variable.

In [54]:
data_limpia.isnull().sum()

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         180
¿Por que no hay solicitud de credito?       294
¿Por que no hubo prueba de manejo ?         318
¿Por que no hubo proceso wow?               309
¿Por que se asigno antes de vistar piso?    320
dtype: int64

In [ ]:
# 6 Valores nulos de las columnas PDM, SDC, Venta y Asesor Asignado 
data_limpia['PDM'] = data_limpia['PDM'].fillna(0.0)
data_limpia['SDC'] = data_limpia['SDC'].fillna(0.0)
data_limpia['Venta'] = data_limpia['Venta'].fillna(0.0)
data_limpia['Asesor Asignado'] = data_limpia['Asesor Asignado'].fillna("Asesor no identificado")

Se utilizó la sustitución por el valor numérico 0, debido a que PDM, SDC y Venta son variables binaria cuyos valores existentes son 0 y 1. El valor 0 permite conservar la estructura de las variables y evitar introducir valores que no pertenecen a sus categorías originales.
Para Asesor asignado utilizó un valor de texto específico "Sin Asesor" para representar los registros donde no existe un asesor asignado. No se utilizó ffill ni bfill, ya que el asesor corresponde a cada cliente y no necesariamente es el mismo que el de los registros contiguos.

In [61]:
data_limpia.isnull().sum()

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           0
SDC                                           0
Venta                                         0
Asesor Asignado                               0
¿Por que no ha visitado la agencia?         180
¿Por que no hay solicitud de credito?       294
¿Por que no hubo prueba de manejo ?         318
¿Por que no hubo proceso wow?               309
¿Por que se asigno antes de vistar piso?    320
dtype: int64

In [65]:
# quitar nulos de las columnas de preguntas
columnas_preguntas = ['¿Por que no ha visitado la agencia?', '¿Por que no hay solicitud de credito?', '¿Por que no hubo prueba de manejo ?','¿Por que no hubo proceso wow?', '¿Por que se asigno antes de vistar piso?']

data_limpia[columnas_preguntas] = data_limpia[columnas_preguntas].fillna("Sin información")

Para las variables correspondientes a preguntas sobre el comportamiento o situación del cliente, se utilizó la sustitución de valores nulos por "Sin información". Estas variables son de tipo texto y sus respuestas representan situaciones particulares de cada cliente, por lo que no es adecuado utilizar métodos estadísticos como la media o mediana, ni métodos como ffill o bfill, ya que podrían asignar una respuesta de otro registro que no corresponde, al utilizar "Sin información" se conservan los registros y ya se diferencia los valores que no cuentan con una respuesta registrada

In [83]:
data_limpia.isnull().sum()

BDC                                         0
Fecha                                       0
Nombre Cliente                              0
Estatus de Lead                             0
Potencial de compra                         0
PDM                                         0
SDC                                         0
Venta                                       0
Asesor Asignado                             0
¿Por que no ha visitado la agencia?         0
¿Por que no hay solicitud de credito?       0
¿Por que no hubo prueba de manejo ?         0
¿Por que no hubo proceso wow?               0
¿Por que se asigno antes de vistar piso?    0
dtype: int64

In [84]:
data_limpia.to_csv('Citas_Digital_Limpio.csv', index=False)

In [21]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
data3["Superficie"]=data3["Superficie"].fillna(round(data2["Superficie"].mean(),1))

In [22]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      6
Fecha Venta     578
Vendedor        578
dtype: int64

In [23]:
#Segundo método de sustitución de valores nulos
#Sustituir valores nulos con mediana
data3["Precio Venta"]=data3["Precio Venta"].fillna(round(data2["Precio Venta"].median(),1))

In [24]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta     578
Vendedor        578
dtype: int64

In [25]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
data3["Fecha Alta"]= data3["Fecha Alta"].fillna(10) 
data3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1121906.0,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1121906.0,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,NaN,NaN

In [26]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta     578
Vendedor        578
dtype: int64

In [27]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data3["Fecha Venta"] =data3["Fecha Venta"].fillna("2030-06-19 00:00:00")

In [28]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [30]:
#Quinto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
data3["Tipo"] =data3["Tipo"].ffill()

In [31]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              0
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [33]:
#Sexto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
#Filtro por columnas
data3["Operación"] =data3["Operación"].bfill()

In [34]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              0
Operación         0
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [35]:
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
data3["Provincia"] =data3["Provincia"].bfill()

In [37]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              0
Operación         0
Provincia         0
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [38]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
#Filtro por columnas
data3["Vendedor"] =data3["Vendedor"].ffill()

In [39]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta      0
Tipo            0
Operación       0
Provincia       0
Superficie      0
Precio Venta    0
Fecha Venta     0
Vendedor        0
dtype: int64

In [40]:
#Corroboramos valores nulos en todo el dataframe
valores_nulos=data3.isnull().sum().sum()
valores_nulos

np.int64(0)

**Método de Eliminación de valores nulos**

In [41]:
#Identificar valores nulos por columna
valores_nulos=data2.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        4
Precio Venta      6
Fecha Venta     578
Vendedor        578
dtype: int64

In [42]:
#Realizamos una copia del dataframe
data4=data2.copy()
data4

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN

In [43]:
#Eliminamos filas con nulos
#No se agrega nada para eliminar filas y 1 para eliminar columnas
data4= data2.dropna()
data4

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
5,2004-01-03 00:00:00,Industrial,Alquiler,Girona,131.0,953156.0,2004-09-05 00:00:00,Pedro
7,2004-01-03 00:00:00,Oficina,Venta,Girona,235.0,2158475.0,2004-10-31 00:00:00,Jesús
...,...,...,...,...,...,...,...,...
3016,2006-12-30 00:00:00,Casa,Alquiler,Barcelona,264.0,1060488.0,2007-04-28 00:00:00,Joaquín
3017,2006-12-31 00:00:00,Oficina,Venta,Lleida,69.0,483828.0,2007-05-05 00:00:00,Pedro
3030,2007-01-07 00:00:00,Industrial,Alquiler,Lleida,196.0,904344.0,2007-04-20 00:00:00,Pedro
3042,2007-01-09 00:00:00,Local,Venta,Lleida,92.0,709596.0,2007-04-17 00:00:00,Carmen
3045,2007-01-10 00:00:00,Parking,Venta,Barcelona,233.0,1077858.0,2007-04-30 00:00:00,María

In [44]:
#Identificar valores nulos por columna
valores_nulos=data4.isnull().sum()
valores_nulos

Fecha Alta      0
Tipo            0
Operación       0
Provincia       0
Superficie      0
Precio Venta    0
Fecha Venta     0
Vendedor        0
dtype: int64

**Comparamos DataFrame3(Sustitución) y Dataframe4(Eliminación)**

In [45]:
data3.info()

<class 'pandas.DataFrame'>
RangeIndex: 3337 entries, 0 to 3336
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fecha Alta    3337 non-null   object
 1   Tipo          3337 non-null   str
 2   Operación     3337 non-null   str
 3   Provincia     3337 non-null   str
 4   Superficie    3337 non-null   float64
 5   Precio Venta  3337 non-null   float64
 6   Fecha Venta   3337 non-null   str
 7   Vendedor      3337 non-null   str
dtypes: float64(2), object(1), str(5)
memory usage: 355.4+ KB

In [46]:
data4.info()

<class 'pandas.DataFrame'>
Index: 2747 entries, 0 to 3045
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fecha Alta    2747 non-null   str
 1   Tipo          2747 non-null   str
 2   Operación     2747 non-null   str
 3   Provincia     2747 non-null   str
 4   Superficie    2747 non-null   float64
 5   Precio Venta  2747 non-null   float64
 6   Fecha Venta   2747 non-null   str
 7   Vendedor      2747 non-null   str
dtypes: float64(2), str(6)
memory usage: 366.9 KB

**Convertir DataSet sin valores nulos a CSV**

In [ ]:
#Convertir DataFrame a CSV
data3.to_csv("inmuebles_sin_nulos.csv")

In [ ]:
#descargar archivo filtrado en csv
#from google.colab import files 
  
  
#files.download("inmuebles_sin_nulos.csv")